export const machineTypeMap: Record<string, string> = {
  '4TOL': '4 Thread Overlock Machine',
  '5TOL': '5 Thread Overlock Machine',
  '6TOL': '6 Thread Overlock Machine',
  'AUBH': 'Auto Button Hole Machine',
  'AUBLLP': 'Auto Belt Loop Attach Machine',
  'AUBPKT': 'Auto Back Pocket Attach Machine',
  'AUCPK': 'Auto Coin Pocket Attach Machine',
  'AUCPKT': 'Auto Coin Pocket Attach Machine',
  'AUCTB': 'Auto Cutting Band Machine',
  'AUELC': 'Auto Elastic Cutting & Joining Machine',
  'AUPAT': 'Auto Pattern Sewer Machine',
  'AUPHCS': 'Auto Pocket Hemming (Chainstitch) Machine',
  'AUPHLS': 'Auto Pocket Hemming (Lockstitch) Machine',
  'AUPKHC': 'Auto Pocket Hemming (Chainstitch) Machine',
  'AUPKHL': 'Auto Pocket Hemming (Lockstitch) Machine',
  'AUSESG': 'Auto Seam Serging Machine',
  'AUWLA': 'Auto Welt Attach Machine',
  'AUWLPK': 'Auto Welt Pocket Machine',
  'AUWPKT': 'Auto Welt Pocket Machine',
  'BH': 'Button Hole Machine',
  'BHCS': 'Chain Stitch Bottom Hem Machine',
  'BHM': 'Blind Hem Machine',
  'BS': 'Button Stitch Machine',
  'BTK': 'Bartack Machine',
  'CADPLT': 'Plotter Machine',
  'CLRCBT': 'Colour Assessment Cabinet (Light Box)',
  'CS': 'Chainstitch Machine',
  'CUBIASC': 'Bias Strip Cutting Machine',
  'CUCUTM': 'Straight Cutting Machine',
  'CUENCT': 'End Cutter Machine',
  'CUFABL': 'Fabric Bale Loader Machine',
  'CUFASP': 'Auto Spreader Machine',
  'CUFBNK': 'Fabric Blanket Machine',
  'CUFCUT': 'Fabric Cutting Machine',
  'CUFDRL': 'Fabric Drill Machine',
  'CUFRIB': 'Fabric Rib Machine',
  'CUFRLX': 'Fabric Relaxing Machine',
  'CUFTMP': 'Fabric Template Machine',
  'CVS': 'Cover Seam Machine',
  'DNLS': 'Double Needle Lockstitch Machine',
  'EH': 'Eyelet Hole Machine',
  'FABINS': 'Fabric Inspection Machine',
  'FABRLX': 'Fabric Relaxing Machine',
  'FBWRAP': 'Button Wrapping Machine',
  'FENDC': 'End Cutter Machine',
  'FHTC': 'Heat Cutter Machine',
  'FHTS': 'Heat Sealer Machine',
  'FL': 'Flatlock Machine',
  'FMTLD': 'Metal Detector Machine',
  'FOA': 'Feed Off the Arm Machine',
  'FPLSTA': 'Plastic Staple Attach Machine',
  'FPNCH': 'Punch Machine',
  'FPUMC': 'Punching Machine',
  'FSMK': 'Smocking Machine',
  'FSNBTN': 'Snap Button Machine',
  'FSNPB': 'Snap Button (Press) Machine',
  'FTHRC': 'Thread Reconning Machine',
  'FTHSK': 'Thread Sucking Machine',
  'FUS': 'Fusing Machine',
  'FVIT': 'Vacuum Iron Table',
  'METDET': 'Metal Detector Machine',
  'MNCS': 'Multi Needle Chainstitch Machine',
  'MNSMK': 'Multi Needle Smocking Machine',
  'PATCUT': 'Pattern Cutter Machine',
  'RFIDCT': 'RFID Counter Top Machine',
  'RFIDTUN': 'RFID Tunnel Machine',
  'SADS': 'Saddle Stitch Machine',
  'SDS': 'Saddle Stitch Machine',
  'SESL': 'Seam Sealing Machine',
  'SNEC': 'Single Needle Edge Cutter Machine',
  'SNLS': 'Single Needle Lockstitch Machine',
  'THDRCN': 'Thread Reconning Machine',
  'THDSUC': 'Thread Sucking Machine',
  'VAIRT': 'Vacuum Iron Table',
  'ZGZG': 'Zigzag Machine',
  'ZZG': 'Zigzag Machine',
};

const fullNameToCode: Record<string, string> = {
  'AUTO BELT LOOP ATTACH': 'AUBLLP',
  'AUTO COIN POCKET SETTER': 'AUCPK',
  'AUTO ELASTIC CUTTING & RING MAKE': 'AUELC',
  'AUTO LOADER': 'AUCTB',
  'AUTO POCKET HEMMING (CHAIN STITCH)': 'AUPKHC',
  'AUTO POCKET HEMMING (LOCK STITCH)': 'AUPKHL',
  'AUTO POCKET SETTER': 'AUBPKT',
  'AUTO SPREADER': 'CUFASP',
  'AUTO WELT POCKET': 'AUWLPK',
  'BARTACK': 'BTK',
  'BLIND STITCH': 'BHM',
  'BOTTOM HEMMING (CHAIN STITCH)': 'BHCS',
  'BOTTOM HEMMING (LOCK+CHAIN STITCH)': 'BHCS',
  'BUTTON HOLE': 'BH',
  'BUTTON STITCH': 'BS',
  'BUTTON WRAPPING MACHINE': 'FBWRAP',
  'CHAIN STITCH': 'CS',
  'COVER SEAM': 'CVS',
  'CUTTING MACHINE': 'CUCUTM',
  'DOUBLE NEEDLE LOCK STITCH': 'DNLS',
  'END CUTTER': 'CUENCT',
  'EYELET HOLE': 'EH',
  'FABRIC RELAX MACHINE': 'FABRLX',
  'FEED OFF THE ARM': 'FOA',
  'FLAT LOCK': 'FL',
  'HEAT CUTTER': 'FHTC',
  'METAL DETECTOR': 'METDET',
  'MULTI NEEDLE CHAIN STITCH': 'MNCS',
  'OVERLOCK (4 THREAD)': '4TOL',
  'OVERLOCK (5 THREAD)': '5TOL',
  'OVERLOCK (6 THREAD)': '6TOL',
  'PATTERN SEWING MACHINE': 'AUPAT',
  'PLASTIC STAPLE ATTACHER': 'FPLSTA',
  'PUNCH MACHINE': 'FPUMC',
  'SEAM SURGING': 'AUSESG',
  'SINGLE NEEDLE LOCK STITCH': 'SNLS',
  'SINGLE NEEDLE LOCK STITCH (EDGE CUTTER)': 'SNEC',
  'SNAP BUTTON': 'FSNBTN',
  'STRAIGHT ROLL CUTTING MACHINE': 'CUCUTM',
  'THREAD RECONE MACHINE': 'THDRCN',
  'THREAD SUCKING': 'THDSUC',
  'VACUUM IRON TABLE': 'VAIRT',
  'VELCRO CUTTER': 'FHTC',
};

export function getMachineTypeDisplay(type: string): { code: string; fullName: string } {
  const t = type?.trim();
  if (!t) return { code: '', fullName: '' };
  if (machineTypeMap[t]) return { code: t, fullName: machineTypeMap[t] };
  const code = fullNameToCode[t];
  if (code && machineTypeMap[code]) return { code, fullName: machineTypeMap[code] };
  if (code) return { code, fullName: t };
  return { code: t, fullName: t };
}

export function getFullName(type: string): string {
  return getMachineTypeDisplay(type).fullName;
}

export const machineTypeOptions = Object.entries(machineTypeMap).map(([code, name]) => ({
  value: code,
  label: `${code} - ${name}`,
}));
